name       : galois
version    : '0.6'
release    : 5
source     :
    - http://mirror.easyname.at/nongnu/galois/source/galois-0.6.tar.gz : de4743c9407afb33a186cd3a3cbf472d790901c41a009bd1775dcf59b466b346
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Galois is a computer game of the "falling blocks" type, but with unique
    features.
description: |
    Galois is a computer game of the "falling blocks" type, but with unique features.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libxml++-2.6)
setup      : |
    sed -i "s/\/games$/\/bin/" src/makefile.in
    sed -i "s/\/games/\/bin/" misc/galois.desktop.in
    %configure
build      : |
    %make
install    : |
    %make_install
